sudo: required
language: node_js
node_js:
  - node
script:
  - npm run test
  - npm run compile
after_success:
  - npm run report-coverage
deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_API_KEY'
  skip_cleanup: true
  on:
    repo: vposd/ts-randomizer
