sudo: required
dist: bionic
language: node_js
jobs:

node_js:
  - stable
script:
  - npm run test
  - npm run build
deploy:
  edge: true
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_API_KEY'
  skip_cleanup: true
  on:
    branch: release
